blueprint:
  name: "Aqara: Locks & Contact Sensors"
  description: |-
    ![Aqara](https://raw.githubusercontent.com/zodyking/Aqara-Lock---Sensor-Blueprint/refs/heads/main/image1.png)

    Automates a smart lock using a door contact sensor with optional spoken announcements.
    Built for reliability and clear speech.

    What it does
    • Auto-locks the door X seconds after the sensor reports CLOSED (single, reliable guard).
    • Cancels the lock if the sensor re-opens during the delay window.
    • Speaks OPENED/CLOSED and LOCKED/UNLOCKED (only after real, confirmed state changes).
    • Optional reminders: repeats a message every X seconds while the door is OPEN
      and/or the lock is UNLOCKED, until it’s resolved (stops immediately when fixed).
    • Optional action: turn on selected lights/switches when the door opens.
    • All speech is queued (mode: queued, max: 2) and a small TTS pre-roll prevents clipped words.

    Setup
    1) Select the contact sensor and the lock.
    2) Choose a TTS engine (e.g., tts.piper) and one or more media_player targets.
    3) Set Auto-lock delay to your preference.
    4) (Optional) Enable reminders and set the interval, and/or select entities to turn on when the door opens.

    Notes
    • The spoken “room” name comes from the entity’s Area (Settings → Areas). Assign your devices to Areas for natural phrases.
    • Lock announcements trigger only when the lock actually reports locked/unlocked (with a brief confirmation).
    • Works with Aqara and other standard Home Assistant binary_sensor/lock entities.

  domain: automation

  input:
    door_sensor:
      name: Contact sensor (door)
      description: |-
        Pick the contact sensor for THIS door.
        For most Aqara sensors, ON = open and OFF = closed.
        Device class should be door or opening.
      selector:
        entity:
          domain: binary_sensor
          device_class: [door, opening]

    lock_entity:
      name: Smart lock
      description: Pick the lock entity to control (Aqara or any lock.*).
      selector:
        entity:
          domain: lock

    door_type:
      name: Door type (affects default TTS wording)
      description: |-
        Controls how the default TTS refers to the opening (used with the Area name):
          • Standard → “<room> door was <action>”
          • Closet   → “<room> closet door was <action>”
          • Entrance → “<room> entrance door was <action>”
      default: standard
      selector:
        select:
          mode: dropdown
          options: [standard, closet, entrance]

    lock_delay:
      name: Auto-lock delay (seconds)
      description: How long after the sensor first reports CLOSED to attempt locking.
      default: 10
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: seconds
          mode: slider

    # ----- Announcements & reminders (no master toggle) -----
    announce_sensor:
      name: Announce sensor open/close
      description: If on, we announce sensor opened/closed events (from your door sensor).
      default: true
      selector: { boolean: {} }

    announce_lock:
      name: Announce lock state changes
      description: If on, we announce locked/unlocked (transitional states are ignored).
      default: true
      selector: { boolean: {} }

    open_reminder_enabled:
      name: Repeat reminder while OPEN
      description: If on, we repeat a reminder message while the door is open until it’s closed.
      default: false
      selector: { boolean: {} }

    unlocked_reminder_enabled:
      name: Repeat reminder while UNLOCKED
      description: If on, we repeat a reminder message while the lock is unlocked until it’s locked.
      default: false
      selector: { boolean: {} }

    reminder_interval:
      name: Reminder interval (seconds)
      description: How often to repeat reminder messages while the condition stays true.
      default: 30
      selector:
        number:
          min: 15
          max: 120
          unit_of_measurement: seconds
          mode: slider

    # ----- Optional “turn on when door opens” -----
    open_turn_on_entities:
      name: Turn on when door opens (optional)
      description: Select lights/switches to turn on immediately when the door opens. Leave empty to disable.
      default: []
      selector:
        entity:
          multiple: true
          domain: [light, switch]

    # ----- TTS plumbing -----
    tts_engine:
      name: TTS engine
      description: Pick your TTS engine entity (e.g., tts.piper). Required if any announcements/reminders are enabled.
      default: ""
      selector:
        entity:
          domain: tts

    media_players:
      name: Speakers for TTS
      description: One or more media_player entities to speak on.
      default: []
      selector:
        entity:
          domain: media_player
          multiple: true

    tts_cache:
      name: Cache TTS audio
      description: Let Home Assistant cache synthesized speech when supported.
      default: false
      selector: { boolean: {} }

    tts_voice:
      name: Voice name (optional)
      description: Only used by engines that support an 'options.voice' parameter (Piper, Edge TTS, Amazon Polly, Google Cloud, ElevenLabs). Leave blank otherwise.
      default: ""
      selector: { text: {} }

    tts_preroll_ms:
      name: TTS pre-roll (milliseconds)
      description: Short delay before speaking to avoid clipping the start of the message.
      default: 150
      selector:
        number:
          min: 0
          max: 300
          step: 10
          unit_of_measurement: ms
          mode: slider

    tts_volume:
      name: TTS volume (%)
      description: Volume level to set on all speakers right BEFORE every TTS message (0–100).
      default: 60
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

mode: queued
max: 2

trigger:
  - id: sensor_opened
    platform: state
    entity_id: !input door_sensor
    to: "on"

  - id: sensor_closed
    platform: state
    entity_id: !input door_sensor
    to: "off"

  - id: lock_changed
    platform: state
    entity_id: !input lock_entity

condition: []

action:
  - variables:
      sensor_ent: !input door_sensor
      lock_ent: !input lock_entity

      # Area → room labels
      sensor_area: "{{ area_name(sensor_ent) }}"
      lock_area: "{{ area_name(lock_ent) }}"
      room_for_sensor: "{{ sensor_area or lock_area or 'Door' }}"
      room_for_lock:   "{{ lock_area or sensor_area or 'Door' }}"

      # Door type → nouning
      door_type_in: !input door_type

      subject_sensor: >-
        {% set r = room_for_sensor %}
        {% set t = (door_type_in or 'standard') %}
        {% if t in ['closet','entrance'] %}
          {{ r }} {{ t }} door
        {% else %}
          {{ r }} door
        {% endif %}
      subject_lock: >-
        {% set r = room_for_lock %}
        {% set t = (door_type_in or 'standard') %}
        {% if t in ['closet','entrance'] %}
          {{ r }} {{ t }} door
        {% else %}
          {{ r }} door
        {% endif %}

      # TTS & controls
      players: !input media_players
      tts_engine_ent: !input tts_engine
      tts_voice_name: !input tts_voice
      tts_preroll_ms: !input tts_preroll_ms
      tts_volume_level: "{{ ( !input tts_volume | int ) / 100 }}"
      has_tts: >-
        {{ (players | length > 0)
           and (tts_engine_ent is string and (tts_engine_ent | length) > 0) }}

      # Only these providers will get options.voice; others (e.g., Google Translate) won't.
      tts_provider: "{{ (tts_engine_ent | string).split('.')[1] | default('') }}"
      use_voice_option: >-
        {{ (tts_voice_name | default('') | trim) != ''
           and tts_provider in ['piper','edge_tts','amazon_polly','polly','google_cloud','elevenlabs'] }}

      # Toggles
      announce_sensor: !input announce_sensor
      announce_lock: !input announce_lock
      open_reminder_enabled: !input open_reminder_enabled
      unlocked_reminder_enabled: !input unlocked_reminder_enabled
      reminder_interval: !input reminder_interval
      open_turn_on_entities: !input open_turn_on_entities

      # Messages
      final_opened: "{{ subject_sensor ~ ' was opened.' }}"
      final_closed: "{{ subject_sensor ~ ' was closed.' }}"
      final_locked: "{{ subject_lock ~ ' was locked.' }}"
      final_unlocked: "{{ subject_lock ~ ' was unlocked.' }}"
      final_open_reminder: "{{ subject_sensor ~ ' is still open.' }}"
      final_unlocked_reminder: "{{ subject_lock ~ ' is still unlocked.' }}"

  - choose:

      # ---------- SENSOR OPENED ----------
      - conditions: [{ condition: trigger, id: sensor_opened }]
        sequence:
          # Optional: turn on entities on open (device errors here are device-side)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (open_turn_on_entities | length) > 0 }}"
                sequence:
                  - service: homeassistant.turn_on
                    target: { entity_id: !input open_turn_on_entities }
            default: []

          # Speak OPENED (no 'voice' for engines that don't support it)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ has_tts and announce_sensor }}"
                sequence:
                  - delay: { milliseconds: "{{ tts_preroll_ms | int }}" }
                  - service: media_player.volume_set
                    target: { entity_id: !input media_players }
                    data: { volume_level: "{{ tts_volume_level }}" }
                  - choose:
                      - conditions: [{ condition: template, value_template: "{{ use_voice_option }}" }]
                        sequence:
                          - service: tts.speak
                            target: { entity_id: !input tts_engine }
                            data:
                              message: "{{ final_opened }}"
                              cache: !input tts_cache
                              media_player_entity_id: !input media_players
                              options: { voice: !input tts_voice }
                    default:
                      - service: tts.speak
                        target: { entity_id: !input tts_engine }
                        data:
                          message: "{{ final_opened }}"
                          cache: !input tts_cache
                          media_player_entity_id: !input media_players
            default: []

          # Repeat reminder while OPEN
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ has_tts and open_reminder_enabled }}"
                sequence:
                  - repeat:
                      while:
                        - condition: template
                          value_template: "{{ states(sensor_ent) == 'on' }}"
                      sequence:
                        - wait_for_trigger:
                            - platform: state
                              entity_id: !input door_sensor
                              to: "off"
                          timeout: { seconds: !input reminder_interval }
                          continue_on_timeout: true
                        - condition: template
                          value_template: "{{ states(sensor_ent) == 'on' }}"
                        - delay: { milliseconds: "{{ tts_preroll_ms | int }}" }
                        - service: media_player.volume_set
                          target: { entity_id: !input media_players }
                          data: { volume_level: "{{ tts_volume_level }}" }
                        - choose:
                            - conditions: [{ condition: template, value_template: "{{ use_voice_option }}" }]
                              sequence:
                                - service: tts.speak
                                  target: { entity_id: !input tts_engine }
                                  data:
                                    message: "{{ final_open_reminder }}"
                                    cache: !input tts_cache
                                    media_player_entity_id: !input media_players
                                    options: { voice: !input tts_voice }
                          default:
                            - service: tts.speak
                              target: { entity_id: !input tts_engine }
                              data:
